#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="divan")]
	public partial class ModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertALUNO(ALUNO instance);
    partial void UpdateALUNO(ALUNO instance);
    partial void DeleteALUNO(ALUNO instance);
    partial void InsertUSUARIO(USUARIO instance);
    partial void UpdateUSUARIO(USUARIO instance);
    partial void DeleteUSUARIO(USUARIO instance);
    partial void InsertGERENCIAR_BAIRRO(GERENCIAR_BAIRRO instance);
    partial void UpdateGERENCIAR_BAIRRO(GERENCIAR_BAIRRO instance);
    partial void DeleteGERENCIAR_BAIRRO(GERENCIAR_BAIRRO instance);
    partial void InsertGERENCIAR_VAN(GERENCIAR_VAN instance);
    partial void UpdateGERENCIAR_VAN(GERENCIAR_VAN instance);
    partial void DeleteGERENCIAR_VAN(GERENCIAR_VAN instance);
    partial void InsertINSTITUICOE(INSTITUICOE instance);
    partial void UpdateINSTITUICOE(INSTITUICOE instance);
    partial void DeleteINSTITUICOE(INSTITUICOE instance);
    partial void InsertMOTORISTA(MOTORISTA instance);
    partial void UpdateMOTORISTA(MOTORISTA instance);
    partial void DeleteMOTORISTA(MOTORISTA instance);
    partial void InsertREPUTACAO(REPUTACAO instance);
    partial void UpdateREPUTACAO(REPUTACAO instance);
    partial void DeleteREPUTACAO(REPUTACAO instance);
    #endregion
		
		public ModelDataContext() : 
				base(global::Model.Properties.Settings.Default.divanConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ALUNO> ALUNOs
		{
			get
			{
				return this.GetTable<ALUNO>();
			}
		}
		
		public System.Data.Linq.Table<USUARIO> USUARIOs
		{
			get
			{
				return this.GetTable<USUARIO>();
			}
		}
		
		public System.Data.Linq.Table<GERENCIAR_BAIRRO> GERENCIAR_BAIRROs
		{
			get
			{
				return this.GetTable<GERENCIAR_BAIRRO>();
			}
		}
		
		public System.Data.Linq.Table<GERENCIAR_VAN> GERENCIAR_VANs
		{
			get
			{
				return this.GetTable<GERENCIAR_VAN>();
			}
		}
		
		public System.Data.Linq.Table<INSTITUICOE> INSTITUICOEs
		{
			get
			{
				return this.GetTable<INSTITUICOE>();
			}
		}
		
		public System.Data.Linq.Table<MOTORISTA> MOTORISTAs
		{
			get
			{
				return this.GetTable<MOTORISTA>();
			}
		}
		
		public System.Data.Linq.Table<REPUTACAO> REPUTACAOs
		{
			get
			{
				return this.GetTable<REPUTACAO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ALUNO")]
	public partial class ALUNO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDALUNO;
		
		private string _NOME;
		
		private string _EMAIL;
		
		private string _TELEFONE;
		
		private string _CELULAR;
		
		private string _SENHA;
		
		private System.Nullable<int> _IDINSTITUICOES;
		
		private string _SOBRENOME;
		
		private EntitySet<REPUTACAO> _REPUTACAOs;
		
		private EntityRef<INSTITUICOE> _INSTITUICOE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDALUNOChanging(int value);
    partial void OnIDALUNOChanged();
    partial void OnNOMEChanging(string value);
    partial void OnNOMEChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnTELEFONEChanging(string value);
    partial void OnTELEFONEChanged();
    partial void OnCELULARChanging(string value);
    partial void OnCELULARChanged();
    partial void OnSENHAChanging(string value);
    partial void OnSENHAChanged();
    partial void OnIDINSTITUICOESChanging(System.Nullable<int> value);
    partial void OnIDINSTITUICOESChanged();
    partial void OnSOBRENOMEChanging(string value);
    partial void OnSOBRENOMEChanged();
    #endregion
		
		public ALUNO()
		{
			this._REPUTACAOs = new EntitySet<REPUTACAO>(new Action<REPUTACAO>(this.attach_REPUTACAOs), new Action<REPUTACAO>(this.detach_REPUTACAOs));
			this._INSTITUICOE = default(EntityRef<INSTITUICOE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDALUNO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDALUNO
		{
			get
			{
				return this._IDALUNO;
			}
			set
			{
				if ((this._IDALUNO != value))
				{
					this.OnIDALUNOChanging(value);
					this.SendPropertyChanging();
					this._IDALUNO = value;
					this.SendPropertyChanged("IDALUNO");
					this.OnIDALUNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOME", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string NOME
		{
			get
			{
				return this._NOME;
			}
			set
			{
				if ((this._NOME != value))
				{
					this.OnNOMEChanging(value);
					this.SendPropertyChanging();
					this._NOME = value;
					this.SendPropertyChanged("NOME");
					this.OnNOMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONE", DbType="VarChar(20)")]
		public string TELEFONE
		{
			get
			{
				return this._TELEFONE;
			}
			set
			{
				if ((this._TELEFONE != value))
				{
					this.OnTELEFONEChanging(value);
					this.SendPropertyChanging();
					this._TELEFONE = value;
					this.SendPropertyChanged("TELEFONE");
					this.OnTELEFONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CELULAR", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CELULAR
		{
			get
			{
				return this._CELULAR;
			}
			set
			{
				if ((this._CELULAR != value))
				{
					this.OnCELULARChanging(value);
					this.SendPropertyChanging();
					this._CELULAR = value;
					this.SendPropertyChanged("CELULAR");
					this.OnCELULARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SENHA", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string SENHA
		{
			get
			{
				return this._SENHA;
			}
			set
			{
				if ((this._SENHA != value))
				{
					this.OnSENHAChanging(value);
					this.SendPropertyChanging();
					this._SENHA = value;
					this.SendPropertyChanged("SENHA");
					this.OnSENHAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDINSTITUICOES", DbType="Int")]
		public System.Nullable<int> IDINSTITUICOES
		{
			get
			{
				return this._IDINSTITUICOES;
			}
			set
			{
				if ((this._IDINSTITUICOES != value))
				{
					if (this._INSTITUICOE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDINSTITUICOESChanging(value);
					this.SendPropertyChanging();
					this._IDINSTITUICOES = value;
					this.SendPropertyChanged("IDINSTITUICOES");
					this.OnIDINSTITUICOESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOBRENOME", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string SOBRENOME
		{
			get
			{
				return this._SOBRENOME;
			}
			set
			{
				if ((this._SOBRENOME != value))
				{
					this.OnSOBRENOMEChanging(value);
					this.SendPropertyChanging();
					this._SOBRENOME = value;
					this.SendPropertyChanged("SOBRENOME");
					this.OnSOBRENOMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ALUNO_REPUTACAO", Storage="_REPUTACAOs", ThisKey="IDALUNO", OtherKey="IDALUNO")]
		public EntitySet<REPUTACAO> REPUTACAOs
		{
			get
			{
				return this._REPUTACAOs;
			}
			set
			{
				this._REPUTACAOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="INSTITUICOE_ALUNO", Storage="_INSTITUICOE", ThisKey="IDINSTITUICOES", OtherKey="IDINSTITUICOES", IsForeignKey=true)]
		public INSTITUICOE INSTITUICOE
		{
			get
			{
				return this._INSTITUICOE.Entity;
			}
			set
			{
				INSTITUICOE previousValue = this._INSTITUICOE.Entity;
				if (((previousValue != value) 
							|| (this._INSTITUICOE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._INSTITUICOE.Entity = null;
						previousValue.ALUNOs.Remove(this);
					}
					this._INSTITUICOE.Entity = value;
					if ((value != null))
					{
						value.ALUNOs.Add(this);
						this._IDINSTITUICOES = value.IDINSTITUICOES;
					}
					else
					{
						this._IDINSTITUICOES = default(Nullable<int>);
					}
					this.SendPropertyChanged("INSTITUICOE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_REPUTACAOs(REPUTACAO entity)
		{
			this.SendPropertyChanging();
			entity.ALUNO = this;
		}
		
		private void detach_REPUTACAOs(REPUTACAO entity)
		{
			this.SendPropertyChanging();
			entity.ALUNO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.USUARIO")]
	public partial class USUARIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDUSUARIO;
		
		private string _EMAIL;
		
		private string _SENHA;
		
		private string _TIPO_USUARIO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDUSUARIOChanging(int value);
    partial void OnIDUSUARIOChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnSENHAChanging(string value);
    partial void OnSENHAChanged();
    partial void OnTIPO_USUARIOChanging(string value);
    partial void OnTIPO_USUARIOChanged();
    #endregion
		
		public USUARIO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUSUARIO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDUSUARIO
		{
			get
			{
				return this._IDUSUARIO;
			}
			set
			{
				if ((this._IDUSUARIO != value))
				{
					this.OnIDUSUARIOChanging(value);
					this.SendPropertyChanging();
					this._IDUSUARIO = value;
					this.SendPropertyChanged("IDUSUARIO");
					this.OnIDUSUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SENHA", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string SENHA
		{
			get
			{
				return this._SENHA;
			}
			set
			{
				if ((this._SENHA != value))
				{
					this.OnSENHAChanging(value);
					this.SendPropertyChanging();
					this._SENHA = value;
					this.SendPropertyChanged("SENHA");
					this.OnSENHAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO_USUARIO", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string TIPO_USUARIO
		{
			get
			{
				return this._TIPO_USUARIO;
			}
			set
			{
				if ((this._TIPO_USUARIO != value))
				{
					this.OnTIPO_USUARIOChanging(value);
					this.SendPropertyChanging();
					this._TIPO_USUARIO = value;
					this.SendPropertyChanged("TIPO_USUARIO");
					this.OnTIPO_USUARIOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GERENCIAR_BAIRRO")]
	public partial class GERENCIAR_BAIRRO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDGERENCIAR_BAIRRO;
		
		private string _BAIRRO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDGERENCIAR_BAIRROChanging(int value);
    partial void OnIDGERENCIAR_BAIRROChanged();
    partial void OnBAIRROChanging(string value);
    partial void OnBAIRROChanged();
    #endregion
		
		public GERENCIAR_BAIRRO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDGERENCIAR_BAIRRO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDGERENCIAR_BAIRRO
		{
			get
			{
				return this._IDGERENCIAR_BAIRRO;
			}
			set
			{
				if ((this._IDGERENCIAR_BAIRRO != value))
				{
					this.OnIDGERENCIAR_BAIRROChanging(value);
					this.SendPropertyChanging();
					this._IDGERENCIAR_BAIRRO = value;
					this.SendPropertyChanged("IDGERENCIAR_BAIRRO");
					this.OnIDGERENCIAR_BAIRROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAIRRO", DbType="VarChar(60)")]
		public string BAIRRO
		{
			get
			{
				return this._BAIRRO;
			}
			set
			{
				if ((this._BAIRRO != value))
				{
					this.OnBAIRROChanging(value);
					this.SendPropertyChanging();
					this._BAIRRO = value;
					this.SendPropertyChanged("BAIRRO");
					this.OnBAIRROChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GERENCIAR_VAN")]
	public partial class GERENCIAR_VAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDGERECIAR_VAN;
		
		private System.Nullable<int> _IDMOTORISTA;
		
		private int _VAGAS;
		
		private System.Nullable<bool> _TV;
		
		private System.Nullable<bool> _AR_CONDICIONADO;
		
		private EntityRef<MOTORISTA> _MOTORISTA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDGERECIAR_VANChanging(int value);
    partial void OnIDGERECIAR_VANChanged();
    partial void OnIDMOTORISTAChanging(System.Nullable<int> value);
    partial void OnIDMOTORISTAChanged();
    partial void OnVAGASChanging(int value);
    partial void OnVAGASChanged();
    partial void OnTVChanging(System.Nullable<bool> value);
    partial void OnTVChanged();
    partial void OnAR_CONDICIONADOChanging(System.Nullable<bool> value);
    partial void OnAR_CONDICIONADOChanged();
    #endregion
		
		public GERENCIAR_VAN()
		{
			this._MOTORISTA = default(EntityRef<MOTORISTA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDGERECIAR_VAN", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDGERECIAR_VAN
		{
			get
			{
				return this._IDGERECIAR_VAN;
			}
			set
			{
				if ((this._IDGERECIAR_VAN != value))
				{
					this.OnIDGERECIAR_VANChanging(value);
					this.SendPropertyChanging();
					this._IDGERECIAR_VAN = value;
					this.SendPropertyChanged("IDGERECIAR_VAN");
					this.OnIDGERECIAR_VANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDMOTORISTA", DbType="Int")]
		public System.Nullable<int> IDMOTORISTA
		{
			get
			{
				return this._IDMOTORISTA;
			}
			set
			{
				if ((this._IDMOTORISTA != value))
				{
					if (this._MOTORISTA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDMOTORISTAChanging(value);
					this.SendPropertyChanging();
					this._IDMOTORISTA = value;
					this.SendPropertyChanged("IDMOTORISTA");
					this.OnIDMOTORISTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VAGAS", DbType="Int NOT NULL")]
		public int VAGAS
		{
			get
			{
				return this._VAGAS;
			}
			set
			{
				if ((this._VAGAS != value))
				{
					this.OnVAGASChanging(value);
					this.SendPropertyChanging();
					this._VAGAS = value;
					this.SendPropertyChanged("VAGAS");
					this.OnVAGASChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TV", DbType="Bit")]
		public System.Nullable<bool> TV
		{
			get
			{
				return this._TV;
			}
			set
			{
				if ((this._TV != value))
				{
					this.OnTVChanging(value);
					this.SendPropertyChanging();
					this._TV = value;
					this.SendPropertyChanged("TV");
					this.OnTVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AR_CONDICIONADO", DbType="Bit")]
		public System.Nullable<bool> AR_CONDICIONADO
		{
			get
			{
				return this._AR_CONDICIONADO;
			}
			set
			{
				if ((this._AR_CONDICIONADO != value))
				{
					this.OnAR_CONDICIONADOChanging(value);
					this.SendPropertyChanging();
					this._AR_CONDICIONADO = value;
					this.SendPropertyChanged("AR_CONDICIONADO");
					this.OnAR_CONDICIONADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MOTORISTA_GERENCIAR_VAN", Storage="_MOTORISTA", ThisKey="IDMOTORISTA", OtherKey="IDMOTORISTA", IsForeignKey=true)]
		public MOTORISTA MOTORISTA
		{
			get
			{
				return this._MOTORISTA.Entity;
			}
			set
			{
				MOTORISTA previousValue = this._MOTORISTA.Entity;
				if (((previousValue != value) 
							|| (this._MOTORISTA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MOTORISTA.Entity = null;
						previousValue.GERENCIAR_VANs.Remove(this);
					}
					this._MOTORISTA.Entity = value;
					if ((value != null))
					{
						value.GERENCIAR_VANs.Add(this);
						this._IDMOTORISTA = value.IDMOTORISTA;
					}
					else
					{
						this._IDMOTORISTA = default(Nullable<int>);
					}
					this.SendPropertyChanged("MOTORISTA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.INSTITUICOES")]
	public partial class INSTITUICOE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDINSTITUICOES;
		
		private string _NOME;
		
		private EntitySet<ALUNO> _ALUNOs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDINSTITUICOESChanging(int value);
    partial void OnIDINSTITUICOESChanged();
    partial void OnNOMEChanging(string value);
    partial void OnNOMEChanged();
    #endregion
		
		public INSTITUICOE()
		{
			this._ALUNOs = new EntitySet<ALUNO>(new Action<ALUNO>(this.attach_ALUNOs), new Action<ALUNO>(this.detach_ALUNOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDINSTITUICOES", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDINSTITUICOES
		{
			get
			{
				return this._IDINSTITUICOES;
			}
			set
			{
				if ((this._IDINSTITUICOES != value))
				{
					this.OnIDINSTITUICOESChanging(value);
					this.SendPropertyChanging();
					this._IDINSTITUICOES = value;
					this.SendPropertyChanged("IDINSTITUICOES");
					this.OnIDINSTITUICOESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOME", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string NOME
		{
			get
			{
				return this._NOME;
			}
			set
			{
				if ((this._NOME != value))
				{
					this.OnNOMEChanging(value);
					this.SendPropertyChanging();
					this._NOME = value;
					this.SendPropertyChanged("NOME");
					this.OnNOMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="INSTITUICOE_ALUNO", Storage="_ALUNOs", ThisKey="IDINSTITUICOES", OtherKey="IDINSTITUICOES")]
		public EntitySet<ALUNO> ALUNOs
		{
			get
			{
				return this._ALUNOs;
			}
			set
			{
				this._ALUNOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ALUNOs(ALUNO entity)
		{
			this.SendPropertyChanging();
			entity.INSTITUICOE = this;
		}
		
		private void detach_ALUNOs(ALUNO entity)
		{
			this.SendPropertyChanging();
			entity.INSTITUICOE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MOTORISTA")]
	public partial class MOTORISTA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDMOTORISTA;
		
		private int _IDUSUARIO;
		
		private string _NOME;
		
		private string _SOBRENOME;
		
		private string _EMAIL;
		
		private string _TELEFONE;
		
		private string _CELULAR;
		
		private string _SENHA;
		
		private EntitySet<GERENCIAR_VAN> _GERENCIAR_VANs;
		
		private EntitySet<REPUTACAO> _REPUTACAOs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDMOTORISTAChanging(int value);
    partial void OnIDMOTORISTAChanged();
    partial void OnIDUSUARIOChanging(int value);
    partial void OnIDUSUARIOChanged();
    partial void OnNOMEChanging(string value);
    partial void OnNOMEChanged();
    partial void OnSOBRENOMEChanging(string value);
    partial void OnSOBRENOMEChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnTELEFONEChanging(string value);
    partial void OnTELEFONEChanged();
    partial void OnCELULARChanging(string value);
    partial void OnCELULARChanged();
    partial void OnSENHAChanging(string value);
    partial void OnSENHAChanged();
    #endregion
		
		public MOTORISTA()
		{
			this._GERENCIAR_VANs = new EntitySet<GERENCIAR_VAN>(new Action<GERENCIAR_VAN>(this.attach_GERENCIAR_VANs), new Action<GERENCIAR_VAN>(this.detach_GERENCIAR_VANs));
			this._REPUTACAOs = new EntitySet<REPUTACAO>(new Action<REPUTACAO>(this.attach_REPUTACAOs), new Action<REPUTACAO>(this.detach_REPUTACAOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDMOTORISTA", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDMOTORISTA
		{
			get
			{
				return this._IDMOTORISTA;
			}
			set
			{
				if ((this._IDMOTORISTA != value))
				{
					this.OnIDMOTORISTAChanging(value);
					this.SendPropertyChanging();
					this._IDMOTORISTA = value;
					this.SendPropertyChanged("IDMOTORISTA");
					this.OnIDMOTORISTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUSUARIO", DbType="Int NOT NULL")]
		public int IDUSUARIO
		{
			get
			{
				return this._IDUSUARIO;
			}
			set
			{
				if ((this._IDUSUARIO != value))
				{
					this.OnIDUSUARIOChanging(value);
					this.SendPropertyChanging();
					this._IDUSUARIO = value;
					this.SendPropertyChanged("IDUSUARIO");
					this.OnIDUSUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOME", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NOME
		{
			get
			{
				return this._NOME;
			}
			set
			{
				if ((this._NOME != value))
				{
					this.OnNOMEChanging(value);
					this.SendPropertyChanging();
					this._NOME = value;
					this.SendPropertyChanged("NOME");
					this.OnNOMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOBRENOME", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string SOBRENOME
		{
			get
			{
				return this._SOBRENOME;
			}
			set
			{
				if ((this._SOBRENOME != value))
				{
					this.OnSOBRENOMEChanging(value);
					this.SendPropertyChanging();
					this._SOBRENOME = value;
					this.SendPropertyChanged("SOBRENOME");
					this.OnSOBRENOMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONE", DbType="VarChar(20)")]
		public string TELEFONE
		{
			get
			{
				return this._TELEFONE;
			}
			set
			{
				if ((this._TELEFONE != value))
				{
					this.OnTELEFONEChanging(value);
					this.SendPropertyChanging();
					this._TELEFONE = value;
					this.SendPropertyChanged("TELEFONE");
					this.OnTELEFONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CELULAR", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CELULAR
		{
			get
			{
				return this._CELULAR;
			}
			set
			{
				if ((this._CELULAR != value))
				{
					this.OnCELULARChanging(value);
					this.SendPropertyChanging();
					this._CELULAR = value;
					this.SendPropertyChanged("CELULAR");
					this.OnCELULARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SENHA", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string SENHA
		{
			get
			{
				return this._SENHA;
			}
			set
			{
				if ((this._SENHA != value))
				{
					this.OnSENHAChanging(value);
					this.SendPropertyChanging();
					this._SENHA = value;
					this.SendPropertyChanged("SENHA");
					this.OnSENHAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MOTORISTA_GERENCIAR_VAN", Storage="_GERENCIAR_VANs", ThisKey="IDMOTORISTA", OtherKey="IDMOTORISTA")]
		public EntitySet<GERENCIAR_VAN> GERENCIAR_VANs
		{
			get
			{
				return this._GERENCIAR_VANs;
			}
			set
			{
				this._GERENCIAR_VANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MOTORISTA_REPUTACAO", Storage="_REPUTACAOs", ThisKey="IDMOTORISTA", OtherKey="IDMOTORISTA")]
		public EntitySet<REPUTACAO> REPUTACAOs
		{
			get
			{
				return this._REPUTACAOs;
			}
			set
			{
				this._REPUTACAOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GERENCIAR_VANs(GERENCIAR_VAN entity)
		{
			this.SendPropertyChanging();
			entity.MOTORISTA = this;
		}
		
		private void detach_GERENCIAR_VANs(GERENCIAR_VAN entity)
		{
			this.SendPropertyChanging();
			entity.MOTORISTA = null;
		}
		
		private void attach_REPUTACAOs(REPUTACAO entity)
		{
			this.SendPropertyChanging();
			entity.MOTORISTA = this;
		}
		
		private void detach_REPUTACAOs(REPUTACAO entity)
		{
			this.SendPropertyChanging();
			entity.MOTORISTA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.REPUTACAO")]
	public partial class REPUTACAO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDREPUTACAO;
		
		private System.Nullable<int> _IDMOTORISTA;
		
		private System.Nullable<int> _IDALUNO;
		
		private System.Nullable<int> _CLASSIFICACAO;
		
		private EntityRef<ALUNO> _ALUNO;
		
		private EntityRef<MOTORISTA> _MOTORISTA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDREPUTACAOChanging(int value);
    partial void OnIDREPUTACAOChanged();
    partial void OnIDMOTORISTAChanging(System.Nullable<int> value);
    partial void OnIDMOTORISTAChanged();
    partial void OnIDALUNOChanging(System.Nullable<int> value);
    partial void OnIDALUNOChanged();
    partial void OnCLASSIFICACAOChanging(System.Nullable<int> value);
    partial void OnCLASSIFICACAOChanged();
    #endregion
		
		public REPUTACAO()
		{
			this._ALUNO = default(EntityRef<ALUNO>);
			this._MOTORISTA = default(EntityRef<MOTORISTA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDREPUTACAO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDREPUTACAO
		{
			get
			{
				return this._IDREPUTACAO;
			}
			set
			{
				if ((this._IDREPUTACAO != value))
				{
					this.OnIDREPUTACAOChanging(value);
					this.SendPropertyChanging();
					this._IDREPUTACAO = value;
					this.SendPropertyChanged("IDREPUTACAO");
					this.OnIDREPUTACAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDMOTORISTA", DbType="Int")]
		public System.Nullable<int> IDMOTORISTA
		{
			get
			{
				return this._IDMOTORISTA;
			}
			set
			{
				if ((this._IDMOTORISTA != value))
				{
					if (this._MOTORISTA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDMOTORISTAChanging(value);
					this.SendPropertyChanging();
					this._IDMOTORISTA = value;
					this.SendPropertyChanged("IDMOTORISTA");
					this.OnIDMOTORISTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDALUNO", DbType="Int")]
		public System.Nullable<int> IDALUNO
		{
			get
			{
				return this._IDALUNO;
			}
			set
			{
				if ((this._IDALUNO != value))
				{
					if (this._ALUNO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDALUNOChanging(value);
					this.SendPropertyChanging();
					this._IDALUNO = value;
					this.SendPropertyChanged("IDALUNO");
					this.OnIDALUNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASSIFICACAO", DbType="Int")]
		public System.Nullable<int> CLASSIFICACAO
		{
			get
			{
				return this._CLASSIFICACAO;
			}
			set
			{
				if ((this._CLASSIFICACAO != value))
				{
					this.OnCLASSIFICACAOChanging(value);
					this.SendPropertyChanging();
					this._CLASSIFICACAO = value;
					this.SendPropertyChanged("CLASSIFICACAO");
					this.OnCLASSIFICACAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ALUNO_REPUTACAO", Storage="_ALUNO", ThisKey="IDALUNO", OtherKey="IDALUNO", IsForeignKey=true)]
		public ALUNO ALUNO
		{
			get
			{
				return this._ALUNO.Entity;
			}
			set
			{
				ALUNO previousValue = this._ALUNO.Entity;
				if (((previousValue != value) 
							|| (this._ALUNO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ALUNO.Entity = null;
						previousValue.REPUTACAOs.Remove(this);
					}
					this._ALUNO.Entity = value;
					if ((value != null))
					{
						value.REPUTACAOs.Add(this);
						this._IDALUNO = value.IDALUNO;
					}
					else
					{
						this._IDALUNO = default(Nullable<int>);
					}
					this.SendPropertyChanged("ALUNO");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MOTORISTA_REPUTACAO", Storage="_MOTORISTA", ThisKey="IDMOTORISTA", OtherKey="IDMOTORISTA", IsForeignKey=true)]
		public MOTORISTA MOTORISTA
		{
			get
			{
				return this._MOTORISTA.Entity;
			}
			set
			{
				MOTORISTA previousValue = this._MOTORISTA.Entity;
				if (((previousValue != value) 
							|| (this._MOTORISTA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MOTORISTA.Entity = null;
						previousValue.REPUTACAOs.Remove(this);
					}
					this._MOTORISTA.Entity = value;
					if ((value != null))
					{
						value.REPUTACAOs.Add(this);
						this._IDMOTORISTA = value.IDMOTORISTA;
					}
					else
					{
						this._IDMOTORISTA = default(Nullable<int>);
					}
					this.SendPropertyChanged("MOTORISTA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
